---
title: "Edward Quinn's CV"
author: Edward Quinn
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

```{css, echo=FALSE}
#title h1 {
  text-transform: unset;
}
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1JPc2OngSwnL1N-eBarY2FPVW-ptqk5EUsFds0syQupw/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}

# Build interactive network of positions colored by section
# and connected if they occurred in the same year
#datadrivencv::build_network_logo(CV$entries_data)

```


```{r}
# 
# if(params$pdf_mode){
#   cat("View this CV online with links at _C:/Users/Edward Quinn/Desktop/build_resume/edward_quinn.html_")
# } else {
#   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](C:/Users/Edward Quinn/Desktop/build_resume/edward_quinn.pdf)")
# }

```

Contact {#contact}
--------------------------------------------------------------------------------



```{r print contact information}

CV %>% print_contact_info()

```



Technical Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

Last updated on `r Sys.Date()`.



Main
================================================================================

Edward Quinn, PhD, MPH {#title}
--------------------------------------------------------------------------------

```{r intro printer}

# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 

```

Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r research experience printer}

CV %<>% print_section('experience')

```

::: aside
```{r print experience aside}

CV %<>% print_text_block('experience_aside')



```
:::

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r education printer}

CV %<>% print_section('education')

```




<!-- These breaks just force a new page so section doesnt get cut off -->



::: aside
```{r print education experience aside}

#CV %<>% print_text_block('education_aside')


```
:::



```{r print teaching positions}

# CV %<>% print_section('teaching_positions')

```

<br>
<br>

<!-- Health Research Publications {data-icon=book} -->
<!-- -------------------------------------------------------------------------------- -->

```{r print publications}

#CV %<>% print_section('academic_articles')

```



```{r print links}

#CV %<>% print_links()

```

